labels:
    - name: bug
      color: ee0701

    - name: dependencies
      color: 0366d6

    - name: enhancement
      color: 0e8a16

    - name: question
      color: cc317c

    - name: security
      color: ee0701

    - name: stale
      color: eeeeee

repository:
    allow_merge_commit: true
    allow_rebase_merge: false
    allow_squash_merge: true
    default_branch: master
    description: "Basic PHP application with authentication enabled at European Commission"
    homepage: https://github.com/ecphp/cas-demo-slim
    topics: authentication,cas
    has_downloads: false
    has_issues: true
    has_pages: false
    has_projects: false
    has_wiki: false
    name: cas-demo-slim
    private: false

teams:
    - name: core
      permission: push
